HEADERS += \
    $$PWD/OperatorsModelAPI.h \
    $$PWD/OpersModelInterface.h \
    $$PWD/OperManagerBase.h \
    $$PWD/OperCreateGeoManagerBase.h \
    $$PWD/OperUndoRedo.h \
    $$PWD/OperImportManager.h \
    $$PWD/OperExportManager.h \
    $$PWD/OperBoolManager.h \
    $$PWD/OperPointManager.h \
    $$PWD/OperCurveManager.h \
    $$PWD/OperSolidManager.h \
    $$PWD/OperPrimitiveManager.h \
    $$PWD/OperSketchManager.h \
    $$PWD/OperMergeEdgeManager.h \
    $$PWD/OperDeleteFloatingEdgeManager.h \
    $$PWD/OperSolidOperManager.h \
    $$PWD/OperFillFaceManager.h \
    $$PWD/OperSurfaceManager.h \
    $$PWD/OperReferenceManager.h \
    $$PWD/OperSplitByMiddleEdgeManager.h \
    $$PWD/OperImprintSolidManager.h \
    $$PWD/OperCompoundManager.h \
    $$PWD/OperSaveHDF5.h \
    $$PWD/OperOpenHDF5.h \
    $$PWD/OperTransformationManager.h \
    $$PWD/OperSplitterManager.h \
    $$PWD/OperFeatureManager.h \
    $$PWD/OperComponentManager.h \
    $$PWD/OperFaceHidden.h \
    $$PWD/OperNBodyUniteManager.h \


SOURCES += \
    $$PWD/OpersModelInterface.cpp \
    $$PWD/OperManagerBase.cpp \
    $$PWD/OperCreateGeoManagerBase.cpp \
    $$PWD/OperUndoRedo.cpp \
    $$PWD/OperImportManager.cpp \
    $$PWD/OperExportManager.cpp \
    $$PWD/OperBoolManager.cpp \
    $$PWD/OperPointManager.cpp \
    $$PWD/OperCurveManager.cpp \
    $$PWD/OperSolidManager.cpp \
    $$PWD/OperPrimitiveManager.cpp \
    $$PWD/OperSketchManager.cpp \
    $$PWD/OperMergeEdgeManager.cpp \
    $$PWD/OperDeleteFloatingEdgeManager.cpp \
    $$PWD/OperSolidOperManager.cpp \
    $$PWD/OperFillFaceManager.cpp \
    $$PWD/OperSurfaceManager.cpp \
    $$PWD/OperReferenceManager.cpp \
    $$PWD/OperSplitByMiddleEdgeManager.cpp \
    $$PWD/OperImprintSolidManager.cpp \
    $$PWD/OperCompoundManager.cpp \
    $$PWD/OperSaveHDF5.cpp \
    $$PWD/OperOpenHDF5.cpp \
    $$PWD/OperTransformationManager.cpp \
    $$PWD/OperSplitterManager.cpp \
    $$PWD/OperFeatureManager.cpp \
    $$PWD/OperComponentManager.cpp \
    $$PWD/OperFaceHidden.cpp \
    $$PWD/OperNBodyUniteManager.cpp \