/*
Copyright (c) 2020-2025, Qingdao Digital Intelligent Ship & Ocean Technology Co., Ltd.
All rights reserved.

This file is part of FastCAE and is distributed under the terms of the
BSD 3-Clause License. See the LICENSE file in the project root for details.
*/

#include "FITKOCCHDF5AdaptorSimpleShape.h"
#include "FITK_Interface/FITKInterfaceGeometry/FITKAbsGeoCommand.h"
#include "FITK_Component/FITKGeoCompOCC/FITKAbstractOCCModel.h"

namespace OCC
{
    FITKOCCAdaptorDef(FITKOCCAdaptorModelBox)
    FITKOCCAdaptorDef(FITKOCCAdaptorModelCylinder)
    FITKOCCAdaptorDef(FITKOCCAdaptorModelSphere)
    FITKOCCAdaptorDef(FITKOCCAdaptorModelBool)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoPoint)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoCurveEnd)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoCurveEndDistance)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoCurveRadio)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoPointProjectionOnCurve)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoTwoCurveIntersection)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoPointProjectionOnSurface)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoCurveIntersectionSurface)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelDelete)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelMultiDelete)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoImprintSolid)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelImport)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelExport)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelCompound)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelTrans)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelTransformByTwoPoints)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelTransformByDirAndDis)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelRotate)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelScale)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelLine)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelSegment)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelWire)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelCircle)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelCircleArc)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelThreePointsCircle)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelEllipse)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelEllipseArc)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelHyperbola)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelHyperbolaArc)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelParabola)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelParabolaArc)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelOffsetCurve)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelBeizeByControlPoints)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelBsplineByThroughPoints)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelThreePointsEllipse)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelThreePointsHyperbolae)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelThreePointsParabola)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelCurveProjectionOnSurface)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelTrimmedCurve)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelSurfaceIntersectionSurface)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelBridgeCurve)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelSurfaceEdge)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelOperLine)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelBridgeSurface)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelSolidSurface)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelMultiSectionSurface)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelSweepSurface)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelRevolSurface)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelExtrudeSurface)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelOffsetSurface)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelClosedWireSurface)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelOperFaceFillHoles)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelOperFaceFillGaps)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelOperFaceDeleteFloatingEdge)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelChamferSolid)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelRemoveChamferSolid)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelFilletSolid)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelRemoveFilletSolid)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelDefeatureSolid)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelFillHoleSolid)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelClosedSurfaceSolid)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelExtrudeSolid)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelRevolSolid)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelSweepSolid)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelMultiSectionSolid)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelStiffener)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelNearestPointLine)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelSampleCurve)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelSketch)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoCurveSplitter)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoSurfaceSplitter)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoSolidSplitter)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoInteractionPoint)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelImportFlattenAssembly)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelMirror)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelRectangularPattern)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelCircularPattern)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoDatumPoint)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoDatumLine)
    FITKOCCAdaptorDef(FITKOCCAdaptorModelReferenceLineByIntersectPlanes)
    FITKOCCAdaptorDef(FITKOCCAdaptorModelReferenceLineByByRotateLine)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoDatumPlane)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoReferenceOffsetPlane)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoReferenceThreePointsPlane)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoReferenceEquationPlane)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoReferencePointAndDirectionPlane)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoReferenceRotateFromPlanePlane)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoPart)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoExtractCenter)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelFromMesh)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoOperNBodyUnite)
    FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelConstruction)

        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionEdgeWithParameter)
        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionEdgeWithPoint)
        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionEdgeWithDatumPlane)

        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionFaceWithSketch)
        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionFaceWithTwoPoints)
        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionFaceWithDatumPlane)
        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionFaceWithCurvedPath)
        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionFaceWithExtendFace)
        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionFaceWithIntersectFace)
        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionFaceWithProjectEdges)

        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionSolidWithPlane)
        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionSolidWithExtendFace)
        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionSolidWithSweepEdge)
        FITKOCCAdaptorDef(FITKOCCAdaptorModelPartitionSolidWithSketchPlanar)

        FITKOCCAdaptorDef(FITKOCCAdaptorModelSketchDeleter)

        FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelCoverEdges)
        FITKOCCAdaptorDef(FITKOCCAdaptorGeoStitch)
        FITKOCCAdaptorDef(FITKOCCAdaptorModelReplaceFaces)
        FITKOCCAdaptorDef(FITKOCCAdaptorModelRemoveFace)

        FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelCircularHole)

        FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelRepairSmallEdges)
        FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelRepairSmallFaces)
        FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelExtrudeCut)
        FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelRevolCut)
        FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelSweepCut)
        FITKOCCAdaptorDef(FITKOCCAdaptorGeoModelExportTopos)

}