HEADERS += \
    $$PWD/GUIAnalysisDialogAPI.h \
    $$PWD/GUIMaterialPropDialog.h \
    $$PWD/GUIMaterialJohnsonCookDialog.h \
    $$PWD/GUIMaterialPlasBritDialog.h \
    $$PWD/GUIMaterialHydroDialog.h \
    $$PWD/GUIMaterialTypeDialog.h \
    $$PWD/GUIPropertyDialog.h \
    $$PWD/GUIPropertyBeamSPRDialog.h \
    $$PWD/GUIPropertyBeamSPR_DOF_Dialog.h \
    $$PWD/GUIPropertySandwitchLayerDialog.h \
    $$PWD/GUIPropertySPHDialog.h \
    $$PWD/GUIPropertySolidDialog.h \
    $$PWD/GUIPropertyShellDialog.h \
    $$PWD/GUIPropertyBeamDialog.h \
    $$PWD/GUIPropertySandwichDialog.h \
    $$PWD/GUIPropertyTypeDialog.h \
    $$PWD/GUICurveDialog.h \
    $$PWD/GUIMaterialElasticDialog.h \
    $$PWD/GUIMaterialPlasTabDialog.h \
    $$PWD/GUIRigidWallTypeDialog.h \
    $$PWD/GUIRigidWallDialog.h \
    $$PWD/GUIRigidWallPlaneDialog.h \
    $$PWD/GUIGravityDialog.h \
    $$PWD/GUIInitialFieldTypeDialog.h \
    $$PWD/GUIInitialFieldDialog.h \
    $$PWD/GUIInitialFieldTRADialog.h \
    $$PWD/NodeGroupWidget.h \
    $$PWD/GUIAccelDialog.h \
    $$PWD/GUISectionDialog.h \
    $$PWD/GUICreateSolutionDialog.h \
    $$PWD/GUIRigidWallCylinderDialog.h \
    $$PWD/GUIContactTieDialog.h \
    $$PWD/GUIEOSDialog.h \
    $$PWD/GUIEOSPolynomialDialog.h \
    $$PWD/GUIEOSTypeDialog.h \
    $$PWD/GUIBCSDialog.h \
    $$PWD/GUIContactMultiUsageImpactDialog.h \
    $$PWD/GUIRBodyDialog.h \
    $$PWD/GUIInitialFieldAXISDialog.h \
    $$PWD/GUIFailureModelDialog.h \
    $$PWD/GUIFailureJOHNSON_Dialog.h \
    $$PWD/GUIFailureBIQUAD_Dialog.h \
    $$PWD/GUIFailureModelTypeDialog.h \
    $$PWD/GUIContactCreateDialog.h \

SOURCES += \
    $$PWD/GUIMaterialPropDialog.cpp \
    $$PWD/GUIMaterialJohnsonCookDialog.cpp \
    $$PWD/GUIMaterialPlasBritDialog.cpp \
    $$PWD/GUIMaterialHydroDialog.cpp \
    $$PWD/GUIMaterialTypeDialog.cpp \
    $$PWD/GUIPropertyDialog.cpp \
    $$PWD/GUIPropertyBeamSPRDialog.cpp \
    $$PWD/GUIPropertyBeamSPR_DOF_Dialog.cpp \
    $$PWD/GUIPropertySandwitchLayerDialog.cpp \
    $$PWD/GUIPropertySPHDialog.cpp \
    $$PWD/GUIPropertySolidDialog.cpp \
    $$PWD/GUIPropertyShellDialog.cpp \
    $$PWD/GUIPropertyBeamDialog.cpp \
    $$PWD/GUIPropertySandwichDialog.cpp \
    $$PWD/GUIPropertyTypeDialog.cpp \
    $$PWD/GUICurveDialog.cpp \
    $$PWD/GUIMaterialElasticDialog.cpp \
    $$PWD/GUIMaterialPlasTabDialog.cpp \
    $$PWD/GUIRigidWallTypeDialog.cpp \
    $$PWD/GUIRigidWallDialog.cpp \
    $$PWD/GUIRigidWallPlaneDialog.cpp \
    $$PWD/GUIGravityDialog.cpp \
    $$PWD/GUIInitialFieldTypeDialog.cpp \
    $$PWD/GUIInitialFieldDialog.cpp \
    $$PWD/GUIInitialFieldTRADialog.cpp \
    $$PWD/NodeGroupWidget.cpp \
    $$PWD/GUIAccelDialog.cpp \
    $$PWD/GUISectionDialog.cpp \
    $$PWD/GUICreateSolutionDialog.cpp \
    $$PWD/GUIRigidWallCylinderDialog.cpp \
    $$PWD/GUIContactTieDialog.cpp \
    $$PWD/GUIEOSDialog.cpp \
    $$PWD/GUIEOSPolynomialDialog.cpp \
    $$PWD/GUIEOSTypeDialog.cpp \
    $$PWD/GUIBCSDialog.cpp \
    $$PWD/GUIContactMultiUsageImpactDialog.cpp \
    $$PWD/GUIRBodyDialog.cpp \
    $$PWD/GUIInitialFieldAXISDialog.cpp \
    $$PWD/GUIFailureModelDialog.cpp \
    $$PWD/GUIFailureJOHNSON_Dialog.cpp \
    $$PWD/GUIFailureBIQUAD_Dialog.cpp \
    $$PWD/GUIFailureModelTypeDialog.cpp \
    $$PWD/GUIContactCreateDialog.cpp \

FORMS += \
    $$PWD/GUIMaterialPropDialog.ui \
    $$PWD/GUIMaterialTypeDialog.ui \
    $$PWD/GUIPropertyDialog.ui \
    $$PWD/GUIPropertySandwitchLayerDialog.ui \
    $$PWD/GUIPropertyTypeDialog.ui \
    $$PWD/GUICurveDialog.ui \
    $$PWD/GUIRigidWallTypeDialog.ui \
    $$PWD/GUIRigidWallDialog.ui \
    $$PWD/GUIGravityDialog.ui \
    $$PWD/GUIInitialFieldTypeDialog.ui \
    $$PWD/GUIInitialFieldDialog.ui \
    $$PWD/GUIAccelDialog.ui \
    $$PWD/GUISectionDialog.ui \
    $$PWD/GUICreateSolutionDialog.ui \
    $$PWD/NodeGroupWidget.ui \
    $$PWD/GUIContactTieDialog.ui \
    $$PWD/GUIEOSDialog.ui \
    $$PWD/GUIEOSTypeDialog.ui \
    $$PWD/GUIBCSDialog.ui \
    $$PWD/GUIContactMultiUsageImpactDialog.ui \
    $$PWD/GUIRBodyDialog.ui \
    $$PWD/GUIInitialFieldAXISDialog.ui \
    $$PWD/GUIFailureModelDialog.ui \
    $$PWD/GUIFailureModelTypeDialog.ui \
    $$PWD/GUIContactCreateDialog.ui \

RESOURCES += \
