HEADERS += \
    $$PWD/ComponentInfoDialog.h \
    $$PWD/Curve3DBSplineInfoDialog.h \
    $$PWD/CurveBridgeCurveInfoDialog.h \
    $$PWD/CurveCurveFromSurfaceInfoDialog.h \
    $$PWD/CurveSplitterInfoDialog.h \
    $$PWD/FeatureStiffenerDialog.h \
    $$PWD/GUIDialogAPI.h \
    $$PWD/BoolOperatorInfoDialog.h \
    $$PWD/ChamferInfoDialog.h \
    $$PWD/FilletInfoDialog.h \
    $$PWD/ReferenceLineInfoDialog.h \
    $$PWD/ReferencePlaneInfoDialog.h \
    $$PWD/ReferencePointInfoDialog.h \
    $$PWD/SolidClosedSurfaceInfoDialog.h \
    $$PWD/SolidMultiSectionInfoDialog.h \
    $$PWD/SurfaceBridgeSurfaceInfoDialog.h \
    $$PWD/SurfaceClosedWireInfoDialog.h \
    $$PWD/SurfaceExtrudeInfoDialog.h \
    $$PWD/SurfaceMultiSectionInfoDialog.h \
    $$PWD/SurfaceOffsetInfoDialog.h \
    $$PWD/SurfaceRevolInfoDialog.h \
    $$PWD/SurfaceSurfaceFromSolidInfoDialog.h \
    $$PWD/SurfaceSweepInfoDialog.h \
    $$PWD/SolidExtrudeInfoDialog.h \
    $$PWD/SolidRevolInfoDialog.h \
    $$PWD/SolidSweepInfoDialog.h \
    $$PWD/PrimitivesBoxInfoDialog.h \
    $$PWD/PrimitivesCylinderInfoDialog.h \
    $$PWD/PrimitivesSphereInfoDialog.h \
    $$PWD/MergeEdgeDialog.h \
    $$PWD/DefeatureInfoDialog.h \
    $$PWD/DeleteFloatingEdgeDialog.h \
    $$PWD/PointCoordinateInfoDialog.h \
    $$PWD/PointCurveEndAndDistanceInfoDialog.h \
    $$PWD/PointInterOfCurveAndSurfaceInfoDialog.h \
    $$PWD/PointCurveEndInfoDialog.h \
    $$PWD/PointInterTwoCurveInfoDialog.h \
    $$PWD/PointInteractionInfoDialog.h \
    $$PWD/TransformationInfoDialog.h \
    $$PWD/PointPointProjOnCurveInfoDialog.h \
    $$PWD/PointCurveAndRadioInfoDialog.h \
    $$PWD/PointPointProjOnSurfaceInfoDialog.h \
    $$PWD/CurveCurveProjSurfaceInfoDialog.h \
    $$PWD/CurveThreePointsEllipseInfoDialog.h \
    $$PWD/CurveOffsetCurveInfoDialog.h \
    $$PWD/CurveThreePointsHyperbolaInfoDialog.h \
    $$PWD/CurveSurfaceInterSurfaceInfoDialog.h \  
    $$PWD/CurveThreePointsParabolaInfoDialog.h \
    $$PWD/CurveThreePointsCircleInfoDialog.h \    
    $$PWD/CurveTwoPointsSegmentInfoDialog.h \
    $$PWD/FillFaceInfoDialog.h \
    $$PWD/SplitEdgeMidpointDialog.h \
    $$PWD/ImprintSolidDialog.h \
    $$PWD/AppendCompoundDialog.h \
    $$PWD/RemoveCompoundDialog.h \
    $$PWD/SurfaceSplitterInfoDialog.h \
    $$PWD/SolidSplitterInfoDialog.h \
    $$PWD/FaceHiddenDialog.h \
    $$PWD/NBodyUniteInfoDialog.h \

FORMS += \
    $$PWD/BoolOperatorInfoDialog.ui \
    $$PWD/ChamferInfoDialog.ui \
    $$PWD/ComponentInfoDialog.ui \
    $$PWD/Curve3DBSplineInfoDialog.ui \
    $$PWD/CurveBridgeCurveInfoDialog.ui \
    $$PWD/CurveCurveFromSurfaceInfoDialog.ui \
    $$PWD/CurveSplitterInfoDialog.ui \
    $$PWD/FeatureStiffenerDialog.ui \
    $$PWD/FilletInfoDialog.ui \
    $$PWD/ReferenceLineInfoDialog.ui \
    $$PWD/ReferencePlaneInfoDialog.ui \
    $$PWD/ReferencePointInfoDialog.ui \
    $$PWD/SolidClosedSurfaceInfoDialog.ui \
    $$PWD/SolidMultiSectionInfoDialog.ui \
    $$PWD/SurfaceBridgeSurfaceInfoDialog.ui \
    $$PWD/SurfaceClosedWireInfoDialog.ui \
    $$PWD/SurfaceExtrudeInfoDialog.ui \
    $$PWD/SurfaceMultiSectionInfoDialog.ui \
    $$PWD/SurfaceOffsetInfoDialog.ui \
    $$PWD/SurfaceRevolInfoDialog.ui \
    $$PWD/SurfaceSurfaceFromSolidInfoDialog.ui \
    $$PWD/SurfaceSweepInfoDialog.ui \
    $$PWD/SolidExtrudeInfoDialog.ui \
    $$PWD/SolidRevolInfoDialog.ui \
    $$PWD/SolidSweepInfoDialog.ui \
    $$PWD/PrimitivesBoxInfoDialog.ui \
    $$PWD/PrimitivesCylinderInfoDialog.ui \
    $$PWD/PrimitivesSphereInfoDialog.ui \
    $$PWD/MergeEdgeDialog.ui \
    $$PWD/DefeatureInfoDialog.ui \
    $$PWD/DeleteFloatingEdgeDialog.ui \
    $$PWD/PointCoordinateInfoDialog.ui \
    $$PWD/PointCurveEndAndDistanceInfoDialog.ui \
    $$PWD/PointInterOfCurveAndSurfaceInfoDialog.ui \
    $$PWD/PointCurveEndInfoDialog.ui \
    $$PWD/PointInterTwoCurveInfoDialog.ui \
    $$PWD/PointInteractionInfoDialog.ui \
    $$PWD/TransformationInfoDialog.ui \
    $$PWD/PointPointProjOnCurveInfoDialog.ui \
    $$PWD/PointCurveAndRadioInfoDialog.ui \
    $$PWD/PointPointProjOnSurfaceInfoDialog.ui \
    $$PWD/CurveCurveProjSurfaceInfoDialog.ui \
    $$PWD/CurveThreePointsEllipseInfoDialog.ui \
    $$PWD/CurveOffsetCurveInfoDialog.ui \
    $$PWD/CurveThreePointsHyperbolaInfoDialog.ui \
    $$PWD/CurveSurfaceInterSurfaceInfoDialog.ui \  
    $$PWD/CurveThreePointsParabolaInfoDialog.ui \
    $$PWD/CurveThreePointsCircleInfoDialog.ui \    
    $$PWD/CurveTwoPointsSegmentInfoDialog.ui \
    $$PWD/FillFaceInfoDialog.ui \
    $$PWD/SplitEdgeMidpointDialog.ui \
    $$PWD/ImprintSolidDialog.ui \
    $$PWD/AppendCompoundDialog.ui \
    $$PWD/RemoveCompoundDialog.ui \
    $$PWD/SurfaceSplitterInfoDialog.ui \
    $$PWD/SolidSplitterInfoDialog.ui \
    $$PWD/FaceHiddenDialog.ui \
    $$PWD/NBodyUniteInfoDialog.ui \
    

SOURCES += \
    $$PWD/BoolOperatorInfoDialog.cpp \
    $$PWD/ChamferInfoDialog.cpp \
    $$PWD/ComponentInfoDialog.cpp \
    $$PWD/Curve3DBSplineInfoDialog.cpp \
    $$PWD/CurveBridgeCurveInfoDialog.cpp \
    $$PWD/CurveCurveFromSurfaceInfoDialog.cpp \
    $$PWD/CurveSplitterInfoDialog.cpp \
    $$PWD/FeatureStiffenerDialog.cpp \
    $$PWD/FilletInfoDialog.cpp \
    $$PWD/ReferenceLineInfoDialog.cpp \
    $$PWD/ReferencePlaneInfoDialog.cpp \
    $$PWD/ReferencePointInfoDialog.cpp \
    $$PWD/SolidClosedSurfaceInfoDialog.cpp \
    $$PWD/SolidMultiSectionInfoDialog.cpp \
    $$PWD/SurfaceBridgeSurfaceInfoDialog.cpp \
    $$PWD/SurfaceClosedWireInfoDialog.cpp \
    $$PWD/SurfaceExtrudeInfoDialog.cpp \
    $$PWD/SurfaceMultiSectionInfoDialog.cpp \
    $$PWD/SurfaceOffsetInfoDialog.cpp \
    $$PWD/SurfaceRevolInfoDialog.cpp \
    $$PWD/SurfaceSurfaceFromSolidInfoDialog.cpp \
    $$PWD/SurfaceSweepInfoDialog.cpp \
    $$PWD/SolidExtrudeInfoDialog.cpp \
    $$PWD/SolidRevolInfoDialog.cpp \
    $$PWD/SolidSweepInfoDialog.cpp \
    $$PWD/PrimitivesBoxInfoDialog.cpp \
    $$PWD/PrimitivesCylinderInfoDialog.cpp \
    $$PWD/PrimitivesSphereInfoDialog.cpp \
    $$PWD/MergeEdgeDialog.cpp \
    $$PWD/DefeatureInfoDialog.cpp \
    $$PWD/DeleteFloatingEdgeDialog.cpp \
    $$PWD/PointCoordinateInfoDialog.cpp \
    $$PWD/PointCurveEndAndDistanceInfoDialog.cpp \
    $$PWD/PointInterOfCurveAndSurfaceInfoDialog.cpp \
    $$PWD/PointCurveEndInfoDialog.cpp \
    $$PWD/PointInterTwoCurveInfoDialog.cpp \
    $$PWD/TransformationInfoDialog.cpp \
    $$PWD/PointPointProjOnCurveInfoDialog.cpp \
    $$PWD/PointCurveAndRadioInfoDialog.cpp \
    $$PWD/PointPointProjOnSurfaceInfoDialog.cpp \
    $$PWD/PointInteractionInfoDialog.cpp \
    $$PWD/CurveCurveProjSurfaceInfoDialog.cpp \
    $$PWD/CurveThreePointsEllipseInfoDialog.cpp \
    $$PWD/CurveOffsetCurveInfoDialog.cpp \
    $$PWD/CurveThreePointsHyperbolaInfoDialog.cpp \
    $$PWD/CurveSurfaceInterSurfaceInfoDialog.cpp \  
    $$PWD/CurveThreePointsParabolaInfoDialog.cpp \
    $$PWD/CurveThreePointsCircleInfoDialog.cpp \    
    $$PWD/CurveTwoPointsSegmentInfoDialog.cpp \
    $$PWD/FillFaceInfoDialog.cpp \
    $$PWD/SplitEdgeMidpointDialog.cpp \
    $$PWD/ImprintSolidDialog.cpp \
    $$PWD/AppendCompoundDialog.cpp \
    $$PWD/RemoveCompoundDialog.cpp \
    $$PWD/SurfaceSplitterInfoDialog.cpp \
    $$PWD/SolidSplitterInfoDialog.cpp \
    $$PWD/FaceHiddenDialog.cpp \
    $$PWD/NBodyUniteInfoDialog.cpp \
