HEADERS += \
    $$PWD/FITKOCCExtendTool.h \
    $$PWD/FITKOCCFeature.h \
    $$PWD/FITKOCCReferenceLine.h \
    $$PWD/FITKOCCReferencePlane.h \
    $$PWD/FITKOCCReferencePoint.h \
    $$PWD/FITKOCCModelSketch2D.h \
    $$PWD/FITKGeoCompOCCAPI.h \
    $$PWD/FITKGeoCompOCCInterface.h \
    $$PWD/FITKAbstractOCCModel.h \
    $$PWD/FITKOCCModelSimpleShape.h \
    $$PWD/FITKOCCModelImport.h \
    $$PWD/FITKOCCModelExport.h \
    $$PWD/FITKOCCComandCommon.h \
    $$PWD/FITKOCCOperBool.h \
    $$PWD/FITKOCCModelRefine.h \
    $$PWD/FITKOCCSplitter.h \
    $$PWD/FITKOCCTransformation.h \
    $$PWD/FITKOCCVirtualTopoCreator.h \
    $$PWD/FITKOCCShapeTriangulate.h \
    $$PWD/FITKOCCGeomTools.h \
    $$PWD/FITKOCCModelPoint.h \
    $$PWD/FITKOCCModelCurve.h \
    $$PWD/FITKOCCModelSurface.h \
    $$PWD/FITKOCCModelSolid.h \
    $$PWD/FITKOCCModelOperLine.h \
    $$PWD/FITKOCCModelOperFace.h \
    $$PWD/FITKOCCModelRemoveWireEdges.h \
    $$PWD/FITKOCCModelWireEdgeFromEdge.h \
    $$PWD/FITKOCCModelOperSolid.h \
    $$PWD/FITKOCCModelOperImprintSolid.h \
    $$PWD/FITKOCCModelOperCompound.h \
    $$PWD/FITKOCCDXFReader.h \
    $$PWD/FITKOCCSampleCurve.h \
    $$PWD/FITKOCCModelNearestPointLine.h \
    $$PWD/FITKOCCModelExtractCenter.h \
    $$PWD/FITKOCCModelFilledRectangle.h \
    $$PWD/FITKOCCModelFilledEllipse.h \
    $$PWD/FITKOCCModelFilledPolygon.h \
    $$PWD/FITKOCCModelFilledParaboloid.h \
    $$PWD/FITKOCCModelFromMesh.h \
    $$PWD/FITKOCCModelPart.h \
    $$PWD/FITKOCCModelImportFlattenAssembly.h \
    $$PWD/FITKOCCModelImportedPart.h \
    $$PWD/FITKOCCAlgTools.h \
    $$PWD/FITKOCCNBodyUnite.h \
    $$PWD/FITKOCCModelCut.h \
    $$PWD/FITKOCCModelPartitionEdge.h \
    $$PWD/FITKOCCModelPartitionFace.h \
    $$PWD/FITKOCCModelPartitionSolid.h \
    $$PWD/FITKOCCModelStitch.h \
    $$PWD/FITKOCCModelCircularHole.h \
    $$PWD/FITKOCCGeoSketchDeleter.h \
    $$PWD/FITKOCCModelExportTopos.h \
    $$PWD/FITKShapeFix_FixSmallFace.h \
    $$PWD/FITKOCCModelMergeEdges.h \
    $$PWD/FITKOCCModelMergePart.h \
    $$PWD/FITKOCCModelTransformPart.h \
    $$PWD/FITKOCCModelSplitPart.h \
    $$PWD/FITKOCCModelFromSketch.h \
    $$PWD/FITKOCCModelPlanarShell.h \
    $$PWD/FITKOCCModelOffsetFace.h \
   

SOURCES += \
    $$PWD/FITKOCCFeature.cpp \
    $$PWD/FITKOCCModelSketch2D.cpp \
    $$PWD/FITKGeoCompOCCInterface.cpp \
    $$PWD/FITKAbstractOCCModel.cpp \
    $$PWD/FITKOCCModelSimpleShape.cpp \
    $$PWD/FITKOCCModelImport.cpp \
    $$PWD/FITKOCCModelExport.cpp \
    $$PWD/FITKOCCComandCommon.cpp \
    $$PWD/FITKOCCOperBool.cpp \
    $$PWD/FITKOCCModelRefine.cpp \
    $$PWD/FITKOCCReferenceLine.cpp \
    $$PWD/FITKOCCReferencePlane.cpp \
    $$PWD/FITKOCCReferencePoint.cpp \
    $$PWD/FITKOCCSplitter.cpp \
    $$PWD/FITKOCCTransformation.cpp \
    $$PWD/FITKOCCVirtualTopoCreator.cpp \
    $$PWD/FITKOCCShapeTriangulate.cpp \
    $$PWD/FITKOCCGeomTools.cpp \
    $$PWD/FITKOCCModelPoint.cpp \
    $$PWD/FITKOCCModelCurve.cpp \
    $$PWD/FITKOCCModelSurface.cpp \
    $$PWD/FITKOCCModelSolid.cpp \
    $$PWD/FITKOCCModelOperLine.cpp \
    $$PWD/FITKOCCModelOperFace.cpp \
    $$PWD/FITKOCCModelRemoveWireEdges.cpp \
    $$PWD/FITKOCCModelWireEdgeFromEdge.cpp \
    $$PWD/FITKOCCModelOperSolid.cpp \
    $$PWD/FITKOCCModelOperImprintSolid.cpp \
    $$PWD/FITKOCCModelOperCompound.cpp \
    $$PWD/FITKOCCDXFReader.cpp \
    $$PWD/FITKOCCSampleCurve.cpp \
    $$PWD/FITKOCCModelNearestPointLine.cpp \
    $$PWD/FITKOCCModelExtractCenter.cpp \
    $$PWD/FITKOCCModelFilledRectangle.cpp \
    $$PWD/FITKOCCModelFilledEllipse.cpp \
    $$PWD/FITKOCCModelFilledPolygon.cpp \
    $$PWD/FITKOCCModelFilledParaboloid.cpp \
    $$PWD/FITKOCCModelFromMesh.cpp \
    $$PWD/FITKOCCModelPart.cpp \
    $$PWD/FITKOCCModelImportFlattenAssembly.cpp \
    $$PWD/FITKOCCModelImportedPart.cpp \
    $$PWD/FITKOCCAlgTools.cpp \
    $$PWD/FITKOCCNBodyUnite.cpp \
    $$PWD/FITKOCCModelCut.cpp \
    $$PWD/FITKOCCModelPartitionEdge.cpp \
    $$PWD/FITKOCCModelPartitionFace.cpp \
    $$PWD/FITKOCCModelPartitionSolid.cpp \
    $$PWD/FITKOCCModelStitch.cpp \
    $$PWD/FITKOCCModelCircularHole.cpp \
    $$PWD/FITKOCCGeoSketchDeleter.cpp \
    $$PWD/FITKOCCModelExportTopos.cpp \
    $$PWD/FITKShapeFix_FixSmallFace.cpp \
    $$PWD/FITKOCCModelMergeEdges.cpp \
    $$PWD/FITKOCCModelMergePart.cpp \
    $$PWD/FITKOCCModelTransformPart.cpp \
    $$PWD/FITKOCCModelSplitPart.cpp \
    $$PWD/FITKOCCModelFromSketch.cpp \
    $$PWD/FITKOCCModelPlanarShell.cpp \
    $$PWD/FITKOCCModelOffsetFace.cpp \


DISTFILES += \
    $$PWD/License.txt \
    