HEADERS += \
    $$PWD/FITKAbsGeoFeature.h \
    $$PWD/FITKAbsGeoSplitter.h \
    $$PWD/FITKAbsGeoTransformation.h \
    $$PWD/FITKInterfaceGeometryAPI.h \
    $$PWD/FITKGeoEnum.h \
    $$PWD/PyFITKGeoBehavior.h \
    $$PWD/PyFITKSketch2D.h \
    $$PWD/FITKAbsGeoCommand.h \
    $$PWD/FITKGeoCommandProp.h \
    $$PWD/FITKAbsGeoDelete.h \
    $$PWD/FITKGeoInterfaceFactory.h \
    $$PWD/FITKAbsGeoShapeAgent.h \
    $$PWD/FITKGeoCommandList.h \
    $$PWD/FITKGeoModelManager.h \
    $$PWD/FITKAbsGeoDatum.h \
    $$PWD/FITKAbsGeoSketch2D.h \
    $$PWD/FITKAbsGeoModelBox.h \
    $$PWD/FITKAbsGeoModelCylinder.h \
    $$PWD/FITKAbsGeoModelCone.h \
    $$PWD/FITKAbsGeoModelFrustum.h \
    $$PWD/FITKAbsGeoModelFilledRectangle.h \
    $$PWD/FITKAbsGeoModelFilledEllipse.h \
    $$PWD/FITKAbsGeoModelFilledPolygon.h \
    $$PWD/FITKAbsGeoModelFilledParaboloid.h \
    $$PWD/FITKAbsGeoModelSphere.h \
    $$PWD/FITKAbsGeoModelImport.h \
    $$PWD/FITKAbsGeoModelExport.h \
    $$PWD/FITKAbsGeoOperBool.h \
    $$PWD/FITKGeometryMeshVS.h \
    $$PWD/FITKGeometryMeshEntity.h \
    $$PWD/FITKAbsVirtualTopo.h \
    $$PWD/FITKVirtualTopoManager.h \
    $$PWD/FITKAbsVirtualTopoMapper.h \
    $$PWD/FITKAbsGeomTools.h \
    $$PWD/FITKAbsGeoModelPoint.h \
    $$PWD/FITKAbsGeoModelCurve.h \
    $$PWD/FITKAbsGeoModelSurface.h \
    $$PWD/FITKAbsGeoModelSolid.h \
    $$PWD/FITKAbsGeoModelCut.h \
    $$PWD/FITKAbsGeoModelOperLine.h \
    $$PWD/FITKAbsGeoModelOperFace.h \
    $$PWD/FITKAbsGeoModelOperSolid.h \
    $$PWD/FITKAbsGeoReferencePoint.h \
    $$PWD/FITKAbsGeoReferenceLine.h \
    $$PWD/FITKAbsGeoReferencePlane.h \
    $$PWD/FITKAbsGeoModelOperImprintSolid.h \
    $$PWD/FITKAbsGeoModelOperCompound.h \
    $$PWD/FITKAbsGeoMultiDelete.h \
    $$PWD/FITKAbsGeoPart.h \
    $$PWD/FITKAbsGeoInstance.h \
    $$PWD/FITKGlobalGeoComponent.h \
    $$PWD/FITKAbsGeoImportedPart.h \
    $$PWD/FITKImportFileThread.h \
    $$PWD/FITKAbsConstruction.h \
    $$PWD/FITKExportFileThread.h \
    $$PWD/FITKAbsGeoImportBase.h \
    $$PWD/FITKAbsGeoStitch.h \
    $$PWD/FITKAbsGeoSampleCurve.h \
    $$PWD/FITKAbsGeoCoverEdges.h \
    $$PWD/FITKAbsGeoModelNearestPointLine.h \
    $$PWD/FITKAbsGeoModelExtractCenter.h \
    $$PWD/FITKAbsGeoModelFromMesh.h \
    $$PWD/FITKAbsGeoRepairSmallEdges.h \
    $$PWD/FITKAbsGeoRepairSmallFaces.h \
    $$PWD/FITKAbsGeoModelImportFlattenAssembly.h \
    $$PWD/FITKAbsGeoModelPartitionEdge.h \
    $$PWD/FITKAbsGeoModelPartitionFace.h \
    $$PWD/FITKAbsGeoModelPartitionSolid.h \
    $$PWD/FITKAbsGeoSketchFillet.h \
    $$PWD/FITKAbsGeoSketchDeleter.h \
    $$PWD/FITKAbsExtendTool.h \
    $$PWD/FITKAbsGeoReplaceFaces.h \
    $$PWD/FITKAbsGeoOperNBodyUnite.h \
    $$PWD/FITKAbsGeoVirtualTopoCombine.h \
    $$PWD/FITKAbsGeoModelExportTopos.h \
    $$PWD/FITKAbsGeoMergeEdges.h \
    $$PWD/FITKAbsGeoModelMergePart.h \
    $$PWD/FITKAbsGeoModelTransformPart.h \
    $$PWD/FITKAbsGeoModelSplitPart.h \
    $$PWD/FITKAbsGeoModelFromSketch.h \
    $$PWD/FITKAbsGeoModelPlanarShell.h \
    $$PWD/FITKAbsGeoRemoveWireEdges.h \
    $$PWD/FITKAbsGeoOffsetFace.h \
    $$PWD/FITKAbsGeoModelSolidFromShell.h \
    $$PWD/FITKAbsGeoModelShellFromSolid.h \
    

SOURCES += \
    $$PWD/FITKAbsGeoCommand.cpp \
    $$PWD/FITKGeoCommandProp.cpp \
    $$PWD/FITKAbsGeoDelete.cpp \
    $$PWD/FITKAbsGeoFeature.cpp \
    $$PWD/FITKAbsGeoSplitter.cpp \
    $$PWD/PyFITKGeoBehavior.cpp \
    $$PWD/PyFITKSketch2D.cpp \
    $$PWD/FITKAbsGeoTransformation.cpp \
    $$PWD/FITKGeoInterfaceFactory.cpp \
    $$PWD/FITKAbsGeoShapeAgent.cpp \
    $$PWD/FITKGeoCommandList.cpp \
    $$PWD/FITKGeoModelManager.cpp \
    $$PWD/FITKAbsGeoDatum.cpp \
    $$PWD/FITKAbsGeoSketch2D.cpp \
    $$PWD/FITKAbsGeoModelBox.cpp \
    $$PWD/FITKAbsGeoModelCylinder.cpp \
    $$PWD/FITKAbsGeoModelCone.cpp \
    $$PWD/FITKAbsGeoModelFrustum.cpp \
    $$PWD/FITKAbsGeoModelFilledRectangle.cpp \
    $$PWD/FITKAbsGeoModelFilledEllipse.cpp \
    $$PWD/FITKAbsGeoModelFilledPolygon.cpp \
    $$PWD/FITKAbsGeoModelFilledParaboloid.cpp \
    $$PWD/FITKAbsGeoModelSphere.cpp \
    $$PWD/FITKAbsGeoModelImport.cpp \
    $$PWD/FITKAbsGeoModelExport.cpp \
    $$PWD/FITKAbsGeoOperBool.cpp \
    $$PWD/FITKGeometryMeshVS.cpp \
    $$PWD/FITKGeometryMeshEntity.cpp \
    $$PWD/FITKAbsVirtualTopo.cpp \
    $$PWD/FITKVirtualTopoManager.cpp \
    $$PWD/FITKAbsVirtualTopoMapper.cpp \
    $$PWD/FITKAbsGeomTools.cpp \
    $$PWD/FITKAbsGeoModelPoint.cpp \
    $$PWD/FITKAbsGeoModelCurve.cpp \
    $$PWD/FITKAbsGeoModelSurface.cpp \
    $$PWD/FITKAbsGeoModelSolid.cpp \
    $$PWD/FITKAbsGeoModelCut.cpp \
    $$PWD/FITKAbsGeoModelOperLine.cpp \
    $$PWD/FITKAbsGeoModelOperFace.cpp \
    $$PWD/FITKAbsGeoModelOperSolid.cpp \
    $$PWD/FITKAbsGeoReferencePoint.cpp \
    $$PWD/FITKAbsGeoReferenceLine.cpp \
    $$PWD/FITKAbsGeoReferencePlane.cpp \
    $$PWD/FITKAbsGeoModelOperImprintSolid.cpp \
    $$PWD/FITKAbsGeoModelOperCompound.cpp \
    $$PWD/FITKAbsGeoMultiDelete.cpp \
    $$PWD/FITKAbsGeoPart.cpp \
    $$PWD/FITKAbsGeoInstance.cpp \
    $$PWD/FITKGlobalGeoComponent.cpp \
    $$PWD/FITKAbsGeoImportedPart.cpp \
    $$PWD/FITKImportFileThread.cpp \
    $$PWD/FITKAbsConstruction.cpp \
    $$PWD/FITKExportFileThread.cpp \
    $$PWD/FITKAbsGeoImportBase.cpp \
    $$PWD/FITKAbsGeoStitch.cpp \
    $$PWD/FITKAbsGeoSampleCurve.cpp \
    $$PWD/FITKAbsGeoCoverEdges.cpp \
    $$PWD/FITKAbsGeoModelNearestPointLine.cpp \
    $$PWD/FITKAbsGeoModelExtractCenter.cpp \
    $$PWD/FITKAbsGeoModelFromMesh.cpp \
    $$PWD/FITKAbsGeoRepairSmallEdges.cpp \
    $$PWD/FITKAbsGeoRepairSmallFaces.cpp \
    $$PWD/FITKAbsGeoModelImportFlattenAssembly.cpp \
    $$PWD/FITKAbsGeoModelPartitionEdge.cpp \
    $$PWD/FITKAbsGeoModelPartitionFace.cpp \
    $$PWD/FITKAbsGeoModelPartitionSolid.cpp \
    $$PWD/FITKAbsGeoSketchFillet.cpp \
    $$PWD/FITKAbsGeoSketchDeleter.cpp \
    $$PWD/FITKAbsGeoReplaceFaces.cpp \
    $$PWD/FITKAbsGeoOperNBodyUnite.cpp \
    $$PWD/FITKAbsGeoVirtualTopoCombine.cpp \
    $$PWD/FITKAbsGeoModelExportTopos.cpp \
    $$PWD/FITKAbsGeoMergeEdges.cpp \
    $$PWD/FITKAbsGeoWireEdgeFromEdge.cpp \
    $$PWD/FITKAbsGeoModelMergePart.cpp \
    $$PWD/FITKAbsGeoModelTransformPart.cpp \
    $$PWD/FITKAbsGeoModelSplitPart.cpp \
    $$PWD/FITKAbsGeoModelFromSketch.cpp \
    $$PWD/FITKAbsGeoModelPlanarShell.cpp \
    $$PWD/FITKAbsGeoRemoveWireEdges.cpp \
    $$PWD/FITKAbsGeoOffsetFace.cpp \
    $$PWD/FITKAbsGeoModelSolidFromShell.cpp \
    $$PWD/FITKAbsGeoModelShellFromSolid.cpp \


DISTFILES += \
    $$PWD/License.txt \
      