# 多用途冲击相互作用示例代码

## 示例1：创建多用途冲击相互作用并设置部分参数（指定名称）
p=InterMultiUsageImpact.InterMultiUsageImpact()
p.createInteraction('Interaction-1')
p.setMasterSurface('Surface-1')
p.setNodeGroup('NodeGroup-1')
p.setIthe(1)
p.setIcurv(0)
p.setIadm(0)
p.setFscaleGap(1.0)
p.setGAPmax(0.0)
p.setFpenmax(0.0)
p.setItied(0)
p.setSTmin(0.0)
p.setSTmax(1e30)
p.setMeshSize(0.4)
p.setDtmin(0.0)
p.setStfac(1.0)
p.setFric(0.0)
p.setGapmin(1.0)
p.setTstart(0.0)
p.setTstop(0.0)
p.setIbc(0)
p.setVisS(0.05)
p.setVisF(1.0)
p.setBumult(0.2)
p.setIfric(0)
p.setIfiltr(0)
p.setXfreq(0.0)
p.setSensID(0)
p.setAscaleF(1.0)
p.setFricID(0)
p.setIstf(0)
p.setIgap(0)
p.setIbag(0)
p.setIdel(0)
p.setIremGap(0)
p.setIremI2(0)
p.setInacti(0)
p.setIform(0)
p.setC1(0.0)
p.setC2(0.0)
p.setC3(0.0)
p.setC4(0.0)
p.setC5(0.0)
p.setC6(0.0)
p.setNRadm(0)
p.setPadm(0.0)
p.setAngladm(0.0)
p.setKthe(0.0)
p.setTint(0.0)
p.setItheForm(0)
p.setAscaleK(1.0)
p.setFrad(0.0)
p.setDrad(0.0)
p.setFheats(0.0)
p.setFheatm(0.0)

## 根据相互作用名称获取类型
AI.AI_Solution().getInteractionType('Interaction-1')

## 根据名称获取多用途冲击相互作用操作对象
p=InterMultiUsageImpact.InterMultiUsageImpact.GetInterMultiUsageImpact('Interaction-1')

## 修改名称和基础对象
p.setName('Interaction-2')
p.setMasterSurface('Surface-2')
p.setNodeGroup('NodeGroup-2')

## 设置摩擦和间隙相关参数
p.setFric(0.2)
p.setGapmin(0.5)
p.setFctIDf('Curve-1')
p.setAscaleF(1.0)

## 设置热交换相关参数
p.setIthe(1)
p.setKthe(100.0)
p.setFctIDK('Curve-2')
p.setTint(20.0)
p.setItheForm(0)
p.setAscaleK(1.0)
